### DISCUSSION TITLE
Pull-through Docker Hub cache

### DISCUSSION THREAD

**Discussion by alecmocatta** [runs-on/runs-on#112] [Tips]
A couple days ago we started hitting Docker Hub rate limits even with Docker Pro:

```text
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
toomanyrequests: Too Many Requests (HAP429).
```

Firstly we checked [`public.ecr.aws`](https://public.ecr.aws) but the images aren't on there yet. Docker support suggested spending $10k a year on a service account. Instead we fixed it by putting an [ECR pull-through cache](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html) in front of Docker Hub. Most guides like [WarpBuild's](https://www.warpbuild.com/blog/docker-mirror-setup) are quite involved, and many predate [ECR gaining pull-through support for Docker Hub](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-pull-through-cache-additional-upstream-registries/).

Our solution was simpler but not totally transparent - it required modifying our application code slightly. Sharing it here in case it's of use, or can be improved and even integrated at some point.

```yaml
    - name: docker login
      uses: docker/login-action@v3
      with:
        registry:<aws account id>.dkr.ecr.us-east-1.amazonaws.com

    - name: docker mirror
      if: runner.os == 'Linux'
      run: |
        echo '{"registry-mirrors": ["https://811169010751.dkr.ecr.us-east-1.amazonaws.com"]}' | sudo tee /etc/docker/daemon.json > /dev/null
        echo '0.0.0.0 index.docker.io registry-1.docker.io docker.io' | sudo tee -a /etc/hosts > /dev/null
        sudo systemctl restart docker
        # https://github.com/moby/moby/issues/30880#issuecomment-798807332
        DOCKER_CONFIG=$(jq '.auths |= . + {"https://index.docker.io/v1/": .["811169010751.dkr.ecr.us-east-1.amazonaws.com"]}' ~/.docker/config.json)
        echo "$DOCKER_CONFIG" > ~/.docker/config.json
```

We created the pull-through cache rule with the namespace "docker-hub", added ECR perms to the configured `EC2InstanceCustomPolicy`, and then made 2 tweaks to our application code:

* prepend `docker-hub/` to image names,
* read the auth token from `~/.docker/config.json` to pass to the `/images/create` API call. Most libraries do this automatically but not the Rust one we use [yet](https://github.com/fussybeaver/bollard/issues/155#issuecomment-1477055392). The `docker` cli also does this automatically.

**Comment by crohr** [comment]
Thanks @alecmocatta! This is nice, and it might actually be something I could integrate indeed. I would suggest to at least put in a preinstall section of an image or runner, so that you can simply share that image or runner definition with multiple workflows / repos and not have to re-add the same steps over and over.

I guess I need to read more about the pull-through caches, but why do you need to prepend `docker-hub/` to image names?

**Comment by alecmocatta** [comment]
> why do you need to prepend `docker-hub/` to image names?

This is a limitation of ECR's pull-through functionality unfortunately. When you define a "pull-through cache rule" it requires an image aka repository namespace aka prefix to trigger it. So the `docker-hub/` in `docker pull docker-hub/grafana/grafana` is what triggers the pull-through behaviour.

> so that you can simply share that image or runner definition with multiple workflows / repos and not have to re-add the same steps over and over

We have one repo and one nontrivial workflow so this is fine. I also prefer to keep setup logic as portable as possible and in one place, rather than spread over 2.

**Comment by crohr** [comment]
Thanks! I'm not seeing any real downside of enabling this pull-through cache by default then, since you have to explicitly ask for that `docker-hub/` namespace for it to be used. Maybe just a slight delay while setting up everything, but I guess this could be done in the background.

**Comment by alecmocatta** [comment]
Creating the pull-through cache rule requires a Docker Hub username & access token.

The above `docker mirror` step breaks pulls of images that aren't prefixed with "docker-hub/". Remove that step and applications can still opt-in to the pull-through cache by prepending the registry also: `docker pull <aws account id>.dkr.ecr.us-east-1.amazonaws.com/docker-hub/grafana/grafana`.

**Comment by project0** [comment]
My current solution is to start a local docker registry/distribution service with s3 cache. I am not sure how affective it is yet, but it seem to cache on s3 (does not seem to improve the pull times :-( ). 
It is not a very universal solution as it works only with the default registry. I also looked into the ECR pull through cache, but it does not work transparently well when you use ECR repo prefixes in your rules (what i have in place for other reasons). I guess the only solution is to have a fully dedicated account in place :shrug: . 

However, this is my current solution as action, just added as pre-step in the jobs: 

```yaml
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: runs-on-prepare
description: Prepare runs-on runner instance
runs:
  using: 'composite'
  steps:
    - shell: bash
      if: ${{ env.RUNS_ON_S3_BUCKET_CACHE != '' }}
      env:
        # v2 does not properly support the ec2 instance profile, i guess because of the IMDSv2 token
        REGISTRY_VERSION: 3.0.0-beta.1
      run: |
        sudo mkdir -p /etc/docker/registry
        echo '{"registry-mirrors": ["http://localhost:5000"]}' | sudo install -m644 /dev/stdin /etc/docker/daemon.json

        sudo install -m644 /dev/stdin /etc/docker/registry/config.yml <<EOF
        version: 0.1
        proxy:
          remoteurl: https://registry-1.docker.io
        storage:
          cache:
            blobdescriptor: inmemory
          delete:
            enabled: false
          redirect:
            disable: false
          s3:
            region: ${RUNS_ON_AWS_REGION}
            bucket: ${RUNS_ON_S3_BUCKET_CACHE}
            rootdirectory: cache/global-docker-cache/docker.io/
        http:
          addr: :5000
        EOF

        sudo install -m644 /dev/stdin /usr/lib/systemd/system/docker-registry.service <<EOF
        [Service]
        User=root
        ExecStart=/tmp/docker-registry/registry serve /etc/docker/registry/config.yml
        EOF

        sudo mkdir -p /tmp/docker-registry
        arch=amd64
        [[ $(uname -m) == aarch64 ]] && arch=arm64
        curl -L https://github.com/distribution/distribution/releases/download/v${{env.REGISTRY_VERSION}}/registry_${{env.REGISTRY_VERSION}}_linux_${arch}.tar.gz | sudo tar -xz -C /tmp/docker-registry

        sudo systemctl daemon-reload
        sudo systemctl restart docker-registry docker
```

**Comment by jpalomaki** [comment]
In our setup (not using runs-on.com yet), we run the official registry [image](https://github.com/distribution/distribution) in ECS Fargate, which caches images pulled from dockerhub, and then configure docker on the self-hosted runners like this:

```sh
cat << EOF > /etc/docker/daemon.json
{
  "registry-mirrors": ["https://dockerhub-mirror.<redacted>"]
}
EOF
```

@crohr Can we configure docker registry mirrors for runs-on.com runners, without building a custom AMI, e.g. in a user-data script?

**Reply by crohr** [reply]
Sure, you can use the preinstall script for that: https://runs-on.com/configuration/repo-config/#runnerspreinstall

**Comment by RobertRautenbach** [comment]
@crohr Polite ping just to see if this is on your radar.

It would be fantastic if there were an option similar to `extras=ecr-cache` for enabling the use of a pull through cache at the job level. 
It would  probably require providing some optional parameters during install so our docker hub details can be used to set up the pull through cache automatically. 

We are a small team who enjoy right-sizing jobs and frequently update our CI workflows. We are currently managing by using the [preinstall script](https://runs-on.com/tips/pull-through-docker-hub-cache/), but this requires us to create a named runner for each configuration to be able to use the preinstall script. It's also somewhat annoying to remember to do this each time we create a repo. It would certainly be fantastic if we could add `extras=ecr-pull-through` and be done with it.

**Reply by crohr** [reply]
@RobertRautenbach sorry for the extended delay. Can you post a draft of what your current preinstall does, so that I can see if I can extract the required secrets etc. into stack params or some other means? Wonder if we could use OIDC so that we don't even have to embed credentials?

**Reply by RobertRautenbach** [reply]
Hey @crohr, no worries! Worth splitting this into two layers, because they actually have very different secrets stories:

The pull-through cache rule itself (install-time, one-off): this does need Docker Hub creds in Secrets Manager.
The runner authenticating to ECR (job-time, every run): for `private: true` runners this is already credential-less via the EC2 instance profile, so there's nothing to extract.

**What we do today - install side (manual, done once):**
1. Created a Secrets Manager secret named `ecr-pullthroughcache/docker-hub` holding our Docker Hub username + access token (ECR requires the name prefix and same account/region).
2. Created an ECR pull-through cache rule with upstream namespace docker-hub → Docker Hub, pointed at that secret.
3. Added ecr:GetAuthorizationToken, ecr:BatchGetImage, ecr:GetDownloadUrlForLayer, ecr:BatchCheckLayerAvailability, plus ecr:CreateRepository and ecr:BatchImportUpstreamImage (needed on the first pull of any image so ECR can lazily materialise the cache repo) to the runner instance role.

**What we do today - job side**
Our `.github/runs-on.yml`, with the anchored preinstall reused across every runner:
```yaml
runners:
  ci-test:
    cpu: [4, 4]
    family: ["c7", "m7"]
    image: ubuntu24-full-x64
    extras: ["s3-cache"]
    private: true
    preinstall: &ecr-login |
      su - runner -c "aws ecr get-login-password --region ap-southeast-2 \
        | docker login --username AWS --password-stdin <acct>.dkr.ecr.ap-southeast-2.amazonaws.com"

  ci-lint:
    # …
    preinstall: *ecr-login
```
Note there are no secrets in that preinstall since `aws ecr get-login-password` mints a short-lived token from the instance profile runs-on already attaches.

Then every image in every workflow is currently hand-rewritten to go through the cache namespace, e.g.:
```yaml
container:
  image: <acct>.dkr.ecr.ap-southeast-2.amazonaws.com/docker-hub/library/node:22.22.0-bookworm
services:
  redis:
    image: <acct>.dkr.ecr.ap-southeast-2.amazonaws.com/docker-hub/library/redis:7
  postgres:
    image: <acct>.dkr.ecr.ap-southeast-2.amazonaws.com/docker-hub/library/postgres:17-alpine
```
What I'd love to see runs-on absorb. Either:
1. Install-time stack param: an optional parameter on the install stack that takes the ARN of a pre-existing Secrets Manager secret holding Docker Hub creds. This way the raw username/token never have to live in params at all, the user just creates the ecr-pullthroughcache/docker-hub secret out of band and hands the stack a pointer. 
2. Raw DockerHubUsername / DockerHubAccessToken NoEcho params would also work (but the secret-ARN form feels cleaner.) 

When set, the stack would:
1. Create the ECR pull-through cache rule (docker-hub → registry-1.docker.io) wired to that secret.
2. Extend the runner instance role with the ECR actions listed above.
That turns the whole manual "install side" section above into a single input at stack-install time.

Job-time (ecrPullThroughCache: true on the runner): a boolean on the runner definition that, when true:
1. Injects the aws ecr get-login-password | docker login preinstall automatically, with the account/region derived from the runner's own metadata so there's nothing for the user to template.
2. Configures Docker's registry-mirrors on the runner image so docker.io/library/node:22 transparently resolves through ECR without any workflow rewrites, effectively @alecmocatta's original approach, but baked into the runner instead of each job doing it.
This is the part we still manually hand-prepend everywhere today and would be by far the biggest ergonomics win.

On OIDC specifically: for `private: true` runners the instance profile already gives credential-less auth from IMDS, so OIDC wouldn't really add anything for the runner → ECR hop.
