### DISCUSSION TITLE
Configure default runner and image globally during install

### DISCUSSION THREAD

**Discussion by imunic** [runs-on/runs-on#45] [Ideas]
Passing an optional default runner and/or image during installation via CloudFormation would be great.

This would enable us to keep usage of runs-on as short as:

```
jobs:
  a-job:
    runs-on: runs-on
```

It would also enable the dev teams not to concern themselves with passing a valid runner if they just wanted to run simple jobs out of the box.

**Comment by crohr** [comment]
@imunic would a single default runner field where you can pass `image`, `family`, `spot`, `hdd`, `cpu`, `ram`, `ssh` labels work? Like:

```
family=m7i,image=ubuntu22-full-x64,cpu=4,ssh=false
```

Should other runners inherit those as defaults?

I'm still not sure this is a good idea yet, because this hides some details from developers that don't have access to the stack to see those.

The other option would be to simply put those definitions into a config file in the [special repository](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-member-only-organization-profile-readme) `.github-private` (which would automatically be loaded by RunsOn, assuming you added it the list of repositories it can access):

```yaml
# .github-private/.github/runs-on.yml
runners:
  default-x64:
    family: ["m7i", "m7a", "m6a"]
    cpu: [4],
    ssh: false
    image: ubuntu22-full-x64
  default-arm64
    family: ["m7g"],
    ssh: false
    cpu: [8]
    image: ubuntu22-full-arm64
```

And then, from any other repository, this would work:

```
runs-on: runs-on,runner=default-x64
```

What do you think?
