### DISCUSSION TITLE
Private registry support for job and service containers using AWS ECR?

### DISCUSSION THREAD

**Discussion by ruffsl** [runs-on/runs-on#71] [Q&A] [answered]
GitHub supports using private registries for job and service containers via the added `credentials` element:

``` yaml
jobs:
  build:
    container:
      image: octocat/ci-image:latest
      credentials:
        username: mona
        password: ${{ secrets.docker_hub_password}}
    services:
      db:
        image:  ghcr.io/octocat/testdb:latest
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_password }}
```
- https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/
- https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#defining-the-container-image

This can be simplified/omitted of course when pulling container images from GHCR (within the same GitHub organization) by allocating read access to actions run from a given repo via GitHub's package permission settings:

- https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages

In migrating from GitHub hosted runners to self hosted runners via RunsOn and AWS, There are (AFAIK?) at least three potential directions one could take in facilitating equivalent support for private registries hosted from AWS ECR.

1. Simply add the password for the AWS ECR login to GitHub action secrets and modify the workflow as required:
> Could get tedious in adding/rotating secret values for every required repo if github org wide access isn't needed.

``` yaml
jobs:
  build:
    container:
      image: octocat/ci-image:latest
      credentials:
        username: AWS
        password: ${{ secrets.AWS_ECR_PASSWORD}}
```

2. Use a prior job to output the login credentials so they are made available to the next job via input context:
> Adds additional startup time, and is rather insecure for confidential secrets.

``` yaml
jobs:
  login-to-amazon-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: us-east-1
          mask-aws-account-id: 'false'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      docker_username: ${{ steps.login-ecr.outputs.docker_username_123456789012_dkr_ecr_us_east_1_amazonaws_com }} # More information on these outputs can be found below in the 'Docker Credentials' section
      docker_password: ${{ steps.login-ecr.outputs.docker_password_123456789012_dkr_ecr_us_east_1_amazonaws_com }}

  run-with-internal-service:
    name: Run something with an internal image as a service
    needs: login-to-amazon-ecr
    runs-on: ubuntu-latest
    services:
      internal-service:
        image: ${{ needs.login-to-amazon-ecr.outputs.registry }}/my-ecr-repo:latest
        credentials:
          username: ${{ needs.login-to-amazon-ecr.outputs.docker_username }}
          password: ${{ needs.login-to-amazon-ecr.outputs.docker_password }}
        ports:
          - '80:80'
    steps:
      - name: Run steps in container
        run: echo "run steps in container"
```
- https://github.com/aws-actions/amazon-ecr-login?tab=readme-ov-file#run-an-image-as-a-service

3. Extend the default IAM profile for RunsCon runner to include necessary read access to private ECR repositories?
> Could mimic the out of band configuration of GHCR access via GitHub's package permission settings.
- https://runs-on.com/blog/changelog-v2-2-1/
> "... using the _extends attribute, and a new feature to allow custom IAM policies for runners."

Any thoughts or suggestions? This could probably be a good topic for Reference section of the RunsOn docs.

**Comment by crohr** [comment]
Hi @ruffsl and thanks for the post. Personally I would go with solution 3, since it would be transparent. The only downside is that the policy applies to the whole organization, so you cannot be granular at the repository level.

**Reply by ruffsl** [reply]
> The only downside is that the policy applies to the whole organization, so you cannot be granular at the repository level.

Couldn't this be customized per the `.github-private/.github/runs-on.yml` configuration file for each repo? I guess "precepail of least privilege" would be rather loose here given who ever has push permissions to the main branch of a organization repo (and thus write access to the config file itself). However, in terms of simply "separation of concerns", it would still be helpful to partition CI access for different repos to limit accidental cross-talk or limit impact craters if all code owner are to be trusted.

**Reply by ruffsl** [reply]
@crohr , BTW, is there a complete schema define for RunsOn configuration files? I'd like to know of all the keys names and acceptable value types, and wasn't sure if the example on the docs site is an exhaustive or not:

- https://runs-on.com/reference/configuration/

**Comment by ruffsl** [comment]
@crohr , I was able to login to AWS ECR after provisioning the `runs-on-EC2InstanceRole-***`  role with the permissions for the AWS managed `AmazonEC2ContainerRegistryPowerUser` policy. 

```yaml

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.RUNS_ON_AWS_REGION }}
    - id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - run: |
        echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
```

I could probably narrow those permissions down, but is there really no other way setting credentials for ECR than this:

- https://github.com/aws-actions/amazon-ecr-login?tab=readme-ov-file#run-an-image-as-a-service

Could the runner image be customized to docker login to ECR using it's own IAM profile, `runs-on-EC2InstanceRole-***`?

Tossing around ECR login passwords via inputs in the clear seem a little bazare in order to just spawn job containers.

**Reply by ruffsl** [reply]
Even restoring to the example provided by aws-actions/amazon-ecr-login doesn't seem easely parameterizable, dang it: 

> Change the output variables for a private ECR to docker_username_private_ecr_aws and docker_password_private_ecr_aws respectively instead of a dynamic generated output variable.

- https://github.com/aws-actions/amazon-ecr-login/issues/483
- https://github.com/orgs/community/discussions/62269

**Comment by crohr** [comment]
Indeed this is not convenient nor desirable. I think you should try adding the ECR login steps in a `preinstall` script that you pass as a custom image to RunsOn. Since the ec2 instance profile will have ECR access, it should all work transparently without the need for the first job

**Comment by crohr** [comment, marked as answer]
@ruffsl I have added an example in https://runs-on.com/features/byoi/, as to how you would redefine the base image with a preinstall step. For this to work you would simply need to add the (e.g.) `AmazonEC2ContainerRegistryPowerUser` as the `EC2InstanceCustomPolicy` CloudFormation parameter.


```yaml
# .github/runs-on.yml
images:
  official_image_with_preinstall:
    platform: "linux"
    arch: "x64"
    owner: "135269210855" # RunsOn owner
    name: "runs-on-v2.2-ubuntu22-full-x64-*" # RunsOn x64 most recent image
    # Assuming you have specified a custom policy (`EC2InstanceCustomPolicy`)
    # so that the runner VMs are able to transparently access ECR
    preinstall: |
      #!/bin/bash
      echo "Doing custom things before job starts"
      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
```
