### ISSUE TITLE
Pull-through Docker Hub cache

### ISSUE THREAD

**Issue by alecmocatta** [runs-on/runs-on#100]
A couple days ago we started hitting Docker Hub rate limits even with Docker Pro:

```text
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
toomanyrequests: Too Many Requests (HAP429).
```

Firstly we checked [`public.ecr.aws`](https://public.ecr.aws) but the images aren't on there yet. Docker support suggested spending $10k a year on a service account. Instead we fixed it by putting an [ECR pull-through cache](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html) in front of Docker Hub. Most guides like [WarpBuild's](https://www.warpbuild.com/blog/docker-mirror-setup) are quite involved, and many predate [ECR gaining pull-through support for Docker Hub](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-pull-through-cache-additional-upstream-registries/).

Our solution was simpler but not totally transparent - it required modifying our application code slightly. Sharing it here in case it's of use, or can be improved and even integrated at some point.

```yaml
    - name: docker login
      uses: docker/login-action@v3
      with:
        registry:<aws account id>.dkr.ecr.us-east-1.amazonaws.com

    - name: docker mirror
      if: runner.os == 'Linux'
      run: |
        echo '{"registry-mirrors": ["https://811169010751.dkr.ecr.us-east-1.amazonaws.com"]}' | sudo tee /etc/docker/daemon.json > /dev/null
        echo '0.0.0.0 index.docker.io registry-1.docker.io docker.io' | sudo tee -a /etc/hosts > /dev/null
        sudo systemctl restart docker
        DOCKER_CONFIG=$(jq '.auths |= . + {"https://index.docker.io/v1/": .["811169010751.dkr.ecr.us-east-1.amazonaws.com"]}' ~/.docker/config.json)
        echo "$DOCKER_CONFIG" > ~/.docker/config.json
```

We created the pull-through cache rule with the namespace "docker-hub", added ECR perms to the configured `EC2InstanceCustomPolicy`, and then made 2 tweaks to our application code:

* prepend `docker-hub/` to image names,
* read the auth token from `~/.docker/config.json` to pass to the `/images/create` API call. There are libs that can handle this incl [`docker-credential-helpers`](https://github.com/docker/docker-credential-helpers) and [`docker_credential`](https://github.com/keirlawson/docker_credential). This is only necessary if your application talks directly to the docker daemon via a library, rather than invoking the `docker` cli.
