### ISSUE TITLE
Documentation Issues re: Custom Runner Images

### ISSUE THREAD

**Issue by jonwest** [runs-on/runs-on#128]
Within the documentation for [Custom Runner Images](https://runs-on.com/configuration/custom-images/#custom-runner-images) there are examples configured:
```
images:
  mycustomimage:
    platform: "linux"
    arch: "x64"
    owner: "099720109477" # Official Ubuntu owner
    name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" # Official Ubuntu image
```

In using this example, this does not ever pick up jobs and the jobs stay forever queued.  I know in the "Custom AMI" example you provided you are using the official RunsOn AMIs as a base, is that required?  Is the runner agent installed automatically?

As another issue further in the Custom Runner Images documentation, the example is:
```
 official_image_with_preinstall:
    platform: "linux"
    arch: "x64"
    owner: "135269210855" # RunsOn owner
    name: "runs-on-v2.2-ubuntu22-full-x64-*" # RunsOn x64 most recent image
    # Assuming you have specified a custom policy (`EC2InstanceCustomPolicy`)
    # so that the runner VMs are able to transparently access ECR
    preinstall: |
      #!/bin/bash
      echo "Doing custom things before job starts"
      su - runner "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com"
```

But this also won't work.  Running `su - runner "aws ....."` would try to run the entire quoted string as a single command rather than a command with parameters, you'd need to run `su - runner -c`, but even that won't work because `aws` and `docker` are only within `runner`s path, not `root`s, so you'd also need something like:
```
#!/bin/bash
      echo "Authenticating with ECR...";
      AWS_PATH=$(su - runner -c "which aws");
      DOCKER_PATH=$(su - runner -c "which docker");
      su - runner -c "${AWS_PATH} ecr get-login-password --region us-east-1 | ${DOCKER_PATH} login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com";
```

In any case, the first issue is more pressing, and currently has us blocked.
