### ISSUE TITLE
[Feature Restoration] Multi-AZ NAT Gateway Support

### ISSUE THREAD

**Issue by colstrom** [runs-on/runs-on#165]
According to the [`v2.5.0` Release Notes](https://github.com/runs-on/runs-on/releases/tag/v2.5.0)...

> The stack will now create only 1 managed NAT gateway (instead of 3) when enabling Private mode, to save on costs.

That seems like a reasonable **default** for most cases, but it's a tradeoff against resiliency, right? Can we restore the prior functionality (a NAT Gateway in each AZ) as an opt-in? This also intersects with the Elastic IP allocations.

Perhaps something like:

```yaml
Parameters:
  NatGatewayAvailability:
    Type: String
    Default: SingleAZ
    AllowedValues:
    - SingleAZ
    - MultiAZ
```

If set to `SingleAZ` (default), it would work the way it does now. If set to `MultiAZ` it would work similarly to how it did in `<= v2.4.0`, but with the addition of applying `NatGatewayElasticIPCount` to all NGWs (allocating the same number of EIPs for each), and probably an indication that the costs are proportional to the number of AZs.

That would avoid having to deal with cumbersome things like dividing some number of EIPs between some number of NGWs, and expressing that logic in a CF template seems... tedious _at best_.

Thanks for considering this request! ❤️
