### ISSUE TITLE
job stuck waiting

### ISSUE THREAD

**Issue by filintod** [runs-on/runs-on#168]
At times it happens that a job is never started and just stuck:

```
Requested labels: runs-on, runner=large, run-id=11807933161, spot=capacity-optimized, hdd=80, ssh=false
Job defined at: ......@refs/heads/main
Waiting for a runner to pick up this job...
```

is there any reason for it?

I'm running version: v2.5.4

**Comment by colstrom** [comment]
@filintod Do you have a `large` runner type defined somewhere, such as in a [repository configuration](https://runs-on.com/configuration/repo-config/)?

If not, the `runner=large` label is likely the issue. There's a list of default runner types in the docs [here](https://runs-on.com/runners/linux/), do you encounter the same situation if you use one of those?

**Comment by filintod** [comment]
yes, I do as mentioned on the link in `.github/runs-on.yml`

**Comment by colstrom** [comment]
Ah, it only happens _sometimes_? That's interesting!

It looks like you're doing the [recommended thing](https://runs-on.com/guides/troubleshoot/#long-queuing-time-for-some-workflows) of adding the `run-id` label, which will end up in the CloudWatch logs for the app service. Have you taken a look at those, and if so, did you find anything interesting that might hint at the source of the issue?

**Comment by filintod** [comment]
thanks for the reminder on the logs. Nothing clear, see the queued without saying why, with a set of 6 `queued` entries repeated every few minutes:

- "Performing housekeeping for job id 32895675036"
- "Updated job status: queued, runner name: "
- "Job is not seen as completed yet, checking why..."
- "Instance state for i-0c5bac732cafd3d8e: running"
- "Runner needs to be checked back again (CheckBackCount=1), reenqueuing to the housekeeping queue..."
- "Sending runner to housekeeping queue (CheckBackCount=1)"

**Comment by filintod** [comment]
I can also see before starting this repeated `queued` loop:
- "✅ EC2 Fleet created successfully with instance i-0c5bac732cafd3d8e"
- "✅ JIT token generated successfully for instance i-0c5bac732cafd3d8e"
- "✅ Config uploaded to S3 successfully for instance i-0c5bac732cafd3d8e"
- "🎉 Runner scheduled successfully"
- "Sending runner to housekeeping queue (CheckBackCount=3)"

**Comment by colstrom** [comment]
Hmm. Did you see this sort of thing with prior versions? Looking at the [Changelog](https://runs-on.com/changelog/), it looks like the housekeeping stuff was added around the version you're using or shortly before (and refined a bit over subsequent patches).

The [v2.5.5 Release Notes](https://github.com/runs-on/runs-on/releases/tag/v2.5.5) mention this:

> - Do not attempt to retry runner creation when we know the original request is invalid (e.g. invalid runner configuration due to mismatched labels etc.)

Is it possible for you to try upgrading to that version (or a later one, but those have other changes) to see if you can reproduce the situation?

**Comment by filintod** [comment]
worth a shot. thanks. I'll see when I can do it this week or next.

**Comment by crohr** [comment]
Thanks @colstrom for the help :) And yes @filintod please upgrade to the latest version, this should help.

**Comment by filintod** [comment]
reopening as I'm seeing this issue more often lately.

This is my hypothesis, we have several jobs in a workflow file and many can take a while, if we use run-id=github.run_id, that will actually be the same value for all jobs in the same workflow, so that runner stealing as mentioned: 

```
For instance, if workflow A has labels [runs-on, runner=2cpu-linux-x64, env=staging] and workflow B has labels [runs-on, runner=2cpu-linux-x64] (env=production is inferred), workflow B might steal the runner from workflow A because its labels are a subset of workflow A. You can circumvent this issue by using the run-id label for better uniqueness (although it’s still shared among jobs within the same workflow), but it is recommended to also set workflow B labels to [runs-on, runner=2cpu-linux-x64, env=production] to avoid any issues.
```

so should I add another suffix to the run-id? can it have string values like `-{unique-job-name-in-workflow}`?

**Comment by crohr** [comment]
@filintod yes definitely, please add another label like `tag=job-name` to make labels more deterministic. See the troubleshooting guide for more examples - https://runs-on.com/guides/troubleshoot/#all-jobs-are-queued-indefinitely-or-long-queuing-time-for-some-workflows.

Also worth using the single label specification (with `/` or `,` separators).

**Comment by filintod** [comment]
will try that, closing

**Comment by skyeagle** [comment]
Firstly, thank you for this amazing service, it's a real game-changer!

We experience some really odd but similar issue... One of our deployment jobs hangs at the beginning without any output, just says "Job started...". This job is a deployment job that runs in parallel with another deployment job. We use reusable workflow and unique labels. We tried to rename it and change the order, nothing helps. 

There is a configuration that we use:

#### main.yml
```
  clone:
    if: github.ref_name == 'staging' && github.run_attempt == 1 && vars.CLONE_SYNC == 'true'
    concurrency:
      group: deploy-clone
      cancel-in-progress: false
    uses: ./.github/workflows/deployment-reusable.yml
    with:
      ENVIRONMENT: clone
    secrets: inherit

  staging:
    if: github.ref_name == 'staging' && github.run_attempt == 1
    concurrency:
      group: deploy-staging
      cancel-in-progress: false
    uses: ./.github/workflows/deployment-reusable.yml
    with:
      ENVIRONMENT: staging
    secrets: inherit
```

#### .github/workflows/deployment-reusable.yml
```
jobs:
  deploy:
    environment: ${{ inputs.ENVIRONMENT }}
    concurrency:
      group: ${{ inputs.ENVIRONMENT }}
    runs-on: "runs-on=${{ github.run_id }}/runner=4cpu-linux-arm64/tag=deploy-${{ inputs.ENVIRONMENT }}"
    env:
....
```

Any idea why it might be happening? Thank you in advance!
