### ISSUE TITLE
Bug: Spot retry does not retry other failed or cancelled jobs in a matrix

### ISSUE THREAD

**Issue by ali-kafel** [runs-on/runs-on#192]
Hello,

We were testing out spot retries with runs-on and we noticed an edge case that would be great to fix. When you run a github actions workflow with a matrix with `fail-fast` set to `true` and one of the jobs fails due to a spot interruption the runs-on service will only restart the failed job that was spot interrupted and not the other failed or cancelled jobs in the matrix:

![image](https://github.com/user-attachments/assets/36cc0983-0cec-48b6-afde-69a02f17d4f7)

Here is the workflow I used to test:
```yaml
name: Disaster Recovery Testing
on:
  workflow_dispatch:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  warm_runners:
    runs-on: runs-on=${{ github.run_id }}/env=stg/runner=2cpu-linux-x64/image=customimage/spot=true/retry=when-interrupted
    strategy:
      fail-fast: true
      max-parallel: 100
      matrix:
        name: [01, 02]

    steps:
      - name: sleep-${{ matrix.name }}
        run: |
          echo "Sleeping for 30 minutes: Task ${{ matrix.name }}"
          sleep 1800 # 30 minutes in seconds
```

But ideally we would want runs-on to restart any other failed or cancelled jobs in the matrix.
