### ISSUE TITLE
Repo config with `runs-on.yml`

### ISSUE THREAD

**Issue by joh-klein** [runs-on/runs-on#200]
Is the syntax for the `runs-on-yml` the same as with the job labels?

Is this the same:
```yml
# .github/workflows/ci.yml
runs-on:
  - runs-on=${{ github.run_id }}
  - cpu=2+16
  - ram=8+32
  - family=c7+m7+r7+c8+m8+r8
  - image=ubuntu24-full-arm64
```
as this
```yml
# .github/runs-on.yml
runners:
  flex:
    cpu: [2, 16]
    ram: [8, 32]
    family: ["c7", "m7", "r7", "c8", "m8", "r8"]
    image: ubuntu24-full-arm64

# .github/workflows/ci.yml
runs-on:
  - runs-on=${{ github.run_id }}
  - runner=flex
```
