### ISSUE TITLE
[Feature Request] - Specify tags as job labels

### ISSUE THREAD

**Issue by labeleddata** [runs-on/runs-on#205]
We'd like to be able to set tags on the instances we launch in runs-on. 

Our (current) use case is evaluating/benchmarking different configurations. We would like to set experiments , label the instances with tags based on that experiment, and then view their total cost and cost breakdown in the Cot explorer in AWS, comparing that to speed. 

While doing this through the logs is possible, it's not the experience we would want. 
This is a nice to have not critical for us , but super useful

**Comment by crohr** [comment]
You can actually already do it from a step, using the AWS CLI with the ec2 instance role assigned to the runner. You can get the RUNS_ON_INSTANCE_ID from the env. 

It’s a good idea to add this capability to runs-on/action as well, but no ETA yet

**Comment by labeleddata** [comment]
As users, we’re generally willing to invest more in your platform to prioritize convenience over just enabling possibilities. While we appreciate that everything is technically possible, as engineers and product managers, we strive for simplicity and ease of use so we can focus on creating higher-value solutions.

Specifically, we’d prefer the ability to easily attach tags directly to the job label instead of having to rely on the AWS CLI. Additionally, it would be ideal if these tags were applied at launch rather than being dependent on whether or when a specific step runs.

From my perspective as a PM, most of our engineering team isn’t familiar with the AWS CLI, and we aim to minimize introducing lines of code that we don’t fully understand or that add unnecessary complexity to our workflows.

Simplifying this process would significantly enhance usability and streamline our interactions with your platform.

**Comment by labeleddata** [comment]
Amazing, thank you

**Comment by crohr** [comment]
@labeleddata @christianherweg0807 I am working on that feature, and was wondering if your use cases include specifying tags directly in the `runs-on:` labels? Idea being that they can then be somewhat dynamic:

```yaml
jobs:
  tagged-job:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/tags=custom-tag:custom-value+other-tag-no-value
    steps:
      - run: echo Hello world
```

Issue here is that labels are sensitive to non-ascii characters, so could trigger some weird error cases with GitHub, before RunsOn is able to sanitize them.

I think for now I will just stick with tags defined in a repository config file only:

```yaml
runners:
  runner-with-tags:
    cpu: 2
    image: ubuntu24-full-x64
    family: ["c7", "m7"]
    tags:
      - config-tag:config-value
      - no-value-tag
```

What do you think?
