### ISSUE TITLE
arm instance configuration in runs-on.yml file

### ISSUE THREAD

**Issue by filintod** [runs-on/runs-on#221]
I have this configuration for an ARM instance:

```
  regular-arm:
    cpu: 2
    family: ["m6g", "m7g"]
    ssh: false
    extras: s3-cache
```

but I get this error:

```
* Created at: 2025-01-26T16:03:20Z
* Labels: [runs-on runner=regular-arm run-id=12976220915]
* RunId: 12976220915

operation error EC2: CreateFleet, https response error StatusCode: 400, RequestID: 0ebeef29-c6b7-4d58-8b66-adbf69836244, api error InvalidParameterValue: We couldn't find any instance pools that match your instance requirements. Change your instance requirements, and try again.
```

it works fine if I use one of the runner aliases direct like `2cpu-linux-arm64`. 

So my question is what am I doing wrong? I'm missing something? m6g and m7g are arm instance families
