### ISSUE TITLE
Snooze spot requests when too many evictions in the last X minutes

### ISSUE THREAD

**Issue by crohr** [runs-on/runs-on#226]
Add mechanism to switch to on-demand for e.g. 1h (irrespective of whether spot is enabled) when more than e.g. 2 evictions happened in the last 30 mins.

2 options:
- set global config at the stack level
- set config local to a custom runner? Or local to all runners within a repo?

```yaml
runners:
  custom-runner:
    spot: true
    ...

spot:
  # some way to describe the strategy
```
