### ISSUE TITLE
Accessing ressources in public S3 buckets

### ISSUE THREAD

**Issue by mashehu** [runs-on/runs-on#268]
We have a CI test setup that takes test data from [AWS-igenomes](https://ewels.github.io/AWS-iGenomes/) located at `s3://ngi-igenomes/`.
This works fine on regular GitHub Runners, but fails on runners using runsOn with a 403 S3 permission error, e.g. [here](https://github.com/nf-core/viralrecon/actions/runs/14104385520/job/39509214425?pr=489#step:12:28). There are many things happening in this job, but the gist is that it tries to access `s3://ngi-igenomes/test-data/viralrecon/minion_test/fastq_pass/` and fails.

I tried adding the following policy to the `runs-on-EC2InstanceRole` role:

```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::ngi-igenomes/*"
        }
    ]
```
but no change. 

Is there anything else I can do to fix this access error?

**Comment by crohr** [comment]
@mashehu interesting, thanks for the ping, I will try to reproduce and see how it can be fixed.

**Comment by mashehu** [comment]
trying now adding it to `EC2InstanceCustomPolicy`

**Comment by crohr** [comment]
@mashehu I just tested with no additional policy, and the following works fine:

```yaml
jobs:
  default:
    runs-on: "runs-on=${{github.run_id}}/runner=2cpu-linux-x64"
    steps:
      - name: Test igenomes fetch
        run: |
          mkdir test
          aws s3 --no-sign-request --region eu-west-1 sync s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/b37/ test/
```

![Image](https://github.com/user-attachments/assets/55ec1751-5f3a-44c3-87c9-98c34f463810)

Are you overriding AWS credentials somewhere maybe?
