### ISSUE TITLE
Image on website causes AWS error

### ISSUE THREAD

**Issue by labeleddata** [runs-on/runs-on#314]
Hi,
I hit this error when copy pasting from the website.
Error I got in the AWS logs
```json

{     "level": "error",     "app_environment": "production",  
   "app_stack_name": "runs-on",     "app_version": "v2.6.1",  
   "labels": [         "runs-on=15326078845",         "image=ubuntu24-full-arm64"     ],     "status": "queued",     "run_id": 15326078845,     "deployment_id": 0,     "job_id": 43121038082,     "job_url": "https://github.com/PrimerAI/build-tools/actions/runs/15326078845/job/43121038082",     "job_name": "assert-cache-miss-arm",     "error": "operation error EC2: CreateFleet, https response error StatusCode: 400, RequestID: f7743f2f-7665-446f-8131-d46ce461830b, api error InvalidParameterValue: We couldn't find any instance pools that match your instance requirements. Change your instance requirements, and try again.",     "time": "2025-05-29T14:26:10Z",     "message": "Failed to create fleet due to a user error. Please check your configuration and try again." } 
```

<img width="1465" alt="Image" src="https://github.com/user-attachments/assets/8a080b52-aa4b-4c15-a183-54db933206d0" />

## What I copy pasted

<img width="1223" alt="Image" src="https://github.com/user-attachments/assets/bdf1c0e5-c583-465f-9de0-47ab6ae14e4e" />

## My workflow

```yaml
  assert-cache-miss-arm:
    # This job tests if the cache is hit on a different architecture (ARM).
    # Ideally, changing OS/architecture should result in a cache miss if the cache isn't cross-architecture.
    # If a cache miss is desired here, the DEBUG_CACHE_KEY or cache setup might need adjustment.
    runs-on:
      - runs-on=${{ github.run_id }}
      - image=ubuntu24-full-arm64
    needs: install-dependencies-runson-x64
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/cached-python-setup
        id: cached-python-setup-hit-arm
```

Of note is that the previous job uses 
```yaml
  assert-cache-hit-ubuntu:
    runs-on:
      - runs-on=${{ github.run_id }}
      - image=ubuntu24-full-x64
```
Which works
