### ISSUE TITLE
Allow configuring resource tags in `runs-on` label attribute

### ISSUE THREAD

**Issue by huonw** [runs-on/runs-on#326]
The docs for custom resource tags say: https://runs-on.com/configuration/resource-tags/

> RunsOn does not support adding custom tags to resources directly within the runs-on: attribute of your workflows, because labels have a limited size and have format constraints. It also would make for very long labels.

I think it may be reasonable to allow the use of labels to set custom resource tags, even if the possible values are more restricted than doing it via one of the other routes.

In particular, there's already encouragement to set `tag=<something-unique>` in the label to avoid runner-stealing when there's compatible jobs, e.g. https://runs-on.com/guides/troubleshoot/#all-jobs-are-queued-indefinitely-or-long-queuing-time-for-some-workflows

Thus, if one could set resource tags via labels one can solve two problems at once, by giving each job a unique resource label, e.g. `tags=job_tag=<something-unique>`

- avoid jobs stealing each other's runners
- use that `job_tag` as a cost allocation tag and thus get simple/direct Cost Explorer reports about the cost of specific jobs

What do you think?

---

As always, thanks for RunsOn!

**Comment by crohr** [comment]
If you want to use `job_tag` as a cost allocation tag, I suppose `<something-unique>` would not really be unique for each job if you want to aggregate costs for a specific tag value. So I don't think this would help with the deterministic runner assignment?

I'm still not convinced I should add direct support for tagging at the runs-on: level, because this is a case where you probably want to reference all available tags in a central place, i.e. the config file. But maybe I'm wrong

**Comment by huonw** [comment]
> If you want to use job_tag as a cost allocation tag, I suppose <something-unique> would not really be unique for each job if you want to aggregate costs for a specific tag value. So I don't think this would help with the deterministic runner assignment?

Sorry, I'm not sure I understand. It might be because my description is insufficient, so spelling it out in more detail (my apologies if you already understood this).

Here's what we currently do in our config, tagging each job with a `tag` label specific to the job, which we believe, when combined with `runs-on=${{ github.run_id }}`, ensures every runner's labels correspond to exactly one job (and vice versa) / is fully unique to side-step the queuing issues that you've documented in the troubleshooting page.

```yaml
jobs:
  e2e:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=company_4ish_cpu_spot
      - tag=company-job-e2e
    ...

  pants-tests:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=company_16ish_cpu_spot
      - tag=company-job-pants-tests
    ...

  ...
```

Under my proposal, we could instead write:

```yaml
jobs:
  e2e:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=company_4ish_cpu_spot
      - tags=job_tag=company-job-e2e # changed
    ...

  pants-tests:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=company_16ish_cpu_spot
      - tags=job_tag=company-job-pants-tests # changed
    ...

  ...
```

We still have the label uniqueness for deterministic assignment, but we can now use `job_tag` as a cost allocation tag that might tell us, for instance:

| tag value | cost  (USD) |
|---|---|
| company-job-e2e | 100 |
| company-job-pants-tests | 20 |
| No tag key: job_tag | &lt;rest of our spend&gt; |

(And then we might draw conclusions like: to cost-optimise our CI jobs, the `e2e` job is worth more effort than the `pants-tests` one.)

To do this in the config file, we'd need to define a unique runner instance for every job, effectively duplicating the job configs.
