### ISSUE TITLE
Extending `runs-on.yml` from `.github-private` no longer works

### ISSUE THREAD

**Issue by kevin-poitra** [runs-on/runs-on#63]
I just upgraded my Runs-On instance from v1.7.2 to v2.2.0, and now repositories that rely on extending a `runs-on.yml` file from a `.github-private` repository no longer pull in the image or runner configuration.

My project repo's `.github/runs-on.yml` looks like so:
```yml
_extends: .github-private
```

My `.github-private` repo's `.github/runs-on.yml` is configured as such:
```yml
images:
  linux-image:
    platform: "linux"
    arch: "arm64"
    ami: "ami-058b428b3b45defec"

runners:
  linux-high-cpu:
    cpu: 64
    ram: 256
    family: ["m7g"]
    image: linux-image
    ssh: true
```

And the `deploy.yml` CI script within the project repo is configured to use that `linux-high-cpu` runner like so:
```yml
runs-on: runs-on,runner=linux-high-cpu
```

Runs-On has also been configured to be allowed to access a handful of repositories within my organization, the project repository and `.github-private` being two of them. I double checked this setting after upgrading.

This results in the deployment job waiting for a runner to start the job for forever, constantly retrying the job every 2 minutes. CloudWatch's logs tell me two things:

1: Runs-On is detecting the job successfully. When it goes to add a `WorkflowJob` to the SQS queue, it reports that the `RepoConfig`'s `Images` and `Runners` variables are both null.

2: Eventually when that `WorkflowJob` is processed, it'll fail due to not being able to find a runner with the name `linux-high-cpu` and will throw the following error:

```
"error": "runner label `linux-high-cpu` not found. (If you are using a configuration file, make sure the file is in the main branch. This could also be due to an error when fetching the file from the GitHub API)",
```
