### ISSUE TITLE
Use S3 Cache for docker images pulled as "services"

### ISSUE THREAD

**Issue by hassec** [runs-on/runs-on#83]
Hi there, 

I've seen the examples using an S3 cache to cache docker layers for the `docker/build-push-action@v5
` action. But is it possible to also cache layers that are pulled for images specified in the `services` section of a CI job?

e.g: 

```
...

jobs:
  build:
    runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }}

    services:
      redis:
        image: "redis:7-alpine"
        volumes:
          - redis_data:/data
      localstack:
        image: localstack/localstack

...
```
